/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M15
 * Generated at: 2017-02-24 06:25:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<meta charset=\"UTF-8\">\n");
      out.write("\t<title>Wips-Inspect</title>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"js/menu2/css/style.css\">\n");
      out.write("\t<!-- jquery -->\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery/1.11.1/jquery-1.11.1.min.js\"></script>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"js/jquery/ui/jquery-ui-1.12.1/jquery-ui.css\">\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery/ui/jquery-ui-1.12.1/jquery-ui.js\"></script>\t\n");
      out.write("\t<!-- tablesorter -->\n");
      out.write("\t<link rel=\"stylesheet\" href=\"js/tablesorter-master/css/theme.default.css\">\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/tablesorter-master/js/jquery.tablesorter.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/tablesorter-master/js/jquery.tablesorter.widgets.js\"></script>\n");
      out.write("\t<!-- json2html -->\t\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery.json2html.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/json2html.js\"></script>\t\t\n");
      out.write("\t<!-- https://cdnjs.com/libraries/c3  -->\n");
      out.write("\t<link rel=\"stylesheet\" href=\"js/c3/0.4.11/c3.min.css\"/>\t\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/d3/d3.v3.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/c3/0.4.11/c3.min.js\"></script>\t\n");
      out.write("\t<!-- my js -->\n");
      out.write("\t<script src=\"js/multiCharts.js\"></script>\n");
      out.write("\t<script src=\"js/get_set.js\"></script>\n");
      out.write("\t<!-- js tree -->\n");
      out.write("\t<link rel=\"stylesheet\" href=\"js/vakata-jstree-3.0.4/dist/themes/default/style.css\" />\n");
      out.write("\t<script src=\"js/vakata-jstree-3.0.4/dist/jstree.min.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<!-- chosen (selectbox) -->\n");
      out.write("\t<script src=\"js/chosen/chosen.jquery.min.js\"></script>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"js/chosen/chosen.min.css\" />\n");
      out.write("\t\n");
      out.write("\t<script src=\"js/err.js\"></script>\n");
      out.write("\t<script src=\"js/wifi_protocol.js\"></script>\n");
      out.write("\t\n");
      out.write("\t\t<script src=\"js/inspectChart.js\"></script>\n");
      out.write("\t\t\n");
      out.write("\t<link rel=\"stylesheet\" href=\"js/obvious-buttons.css\" />\n");
      out.write("\t\n");
      out.write("\t<style type=\"text/css\">\n");
      out.write("\t.gree_add_img {\n");
      out.write("\t\tcursor: pointer;\n");
      out.write("\t\tvertical-align: middle;\n");
      out.write("\t}\n");
      out.write("\t.red_remove_img {\n");
      out.write("\t\tcursor: pointer;\n");
      out.write("\t\tvertical-align: middle;\n");
      out.write("\t}\n");
      out.write("\t.legend_img {\n");
      out.write("\t\twidth: 12px;\n");
      out.write("\t\theight: 12px;\n");
      out.write("\t\tcursor: pointer;\n");
      out.write("\t\tvertical-align: middle;\n");
      out.write("\t\tpadding-left: 1px;\n");
      out.write("\t\tpadding-right: 1px;\n");
      out.write("\t\tmargin-bottom: 1px;\n");
      out.write("\t}\n");
      out.write("\t.closeable_img {\n");
      out.write("\t\twidth: 26px;\n");
      out.write("\t\theight: 26px;\n");
      out.write("\t\tcursor: pointer;\n");
      out.write("\t\tvertical-align: middle;\n");
      out.write("\t\tpadding-left: 1px;\n");
      out.write("\t\tpadding-right: 1px;\n");
      out.write("\t\tmargin-bottom: 1px;\n");
      out.write("\t}\n");
      out.write("\t.input_img {\n");
      out.write("\t\twidth: 15px;\n");
      out.write("\t\theight: 15px;\n");
      out.write("\t\tvertical-align: middle;\n");
      out.write("\t}\n");
      out.write("\t.icon_img {\n");
      out.write("\t\twidth: 25px;\n");
      out.write("\t\theight: 25px;\n");
      out.write("\t\tvertical-align: middle;\n");
      out.write("\t\tcursor: pointer;\n");
      out.write("\t}\n");
      out.write("\t* {\n");
      out.write("\t\tfont-size: 13px;\n");
      out.write("\t\tfont-family: Arial, Sans-serif\n");
      out.write("\t}\n");
      out.write("\t.content {\n");
      out.write("\t\tpadding: 10px;\n");
      out.write("\t}\n");
      out.write("\t.main_fieldset {\n");
      out.write("\t\tborder: 2px solid #1F497D;\n");
      out.write("\t\tborder-radius: 5px;\n");
      out.write("\t\tmargin-top: 10px;\n");
      out.write("\t\tmargin-bottom: 10px;\n");
      out.write("\t\tpadding: 10px;\n");
      out.write("\t\tbackground: #ddd;\n");
      out.write("\t}\n");
      out.write("\t.main_fieldset > legend {\n");
      out.write("\t    background: #1F497D;\n");
      out.write("\t    color: #fff;\n");
      out.write("\t    padding: 5px 10px ;\n");
      out.write("\t    font-size: 18px;\n");
      out.write("\t    border-radius: 5px;\n");
      out.write("\t    box-shadow: 0 0 0 5px #ddd;\n");
      out.write("\t    margin-left: 20px;\n");
      out.write("\t}\n");
      out.write("\t.sub_fieldset {\n");
      out.write("\t\tborder: 2px solid #666C73;\n");
      out.write("\t\tborder-radius: 5px;\n");
      out.write("\t\tmargin-top: 30px;\n");
      out.write("\t\tmargin-bottom: 10px;\n");
      out.write("\t\tpadding: 10px;\n");
      out.write("\t\tbackground: #ddd;\n");
      out.write("\t}\n");
      out.write("\t.sub_fieldset > legend {\n");
      out.write("\t    background: #666C73;\n");
      out.write("\t    color: #fff;\n");
      out.write("\t    padding: 5px 10px ;\n");
      out.write("\t    font-size: 15px;\n");
      out.write("\t    border-radius: 5px;\n");
      out.write("\t    box-shadow: 0 0 0 5px #ddd;\n");
      out.write("\t    margin-left: 20px;\n");
      out.write("\t}\n");
      out.write("\tinput[type=text], select {\n");
      out.write("\t    width: 100%;\n");
      out.write("\t    padding: 3px 5px;\n");
      out.write("\t    display: inline-block;\n");
      out.write("\t    border: 1px solid #ccc;\n");
      out.write("\t    border-radius: 4px;\n");
      out.write("\t    box-sizing: border-box;\n");
      out.write("\t    background: #fff;\n");
      out.write("\t}\n");
      out.write("\ttable {\n");
      out.write("\t\twidth: 100%;\n");
      out.write("\t}\n");
      out.write("\t</style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body style=\"background-color: white;\">\n");
      out.write("\t<div id=\"magic\" style=\"width: 100%; height: 100%;\"></div>\n");
      out.write("\t<header>\n");
      out.write("\t\t<nav id='cssmenu'>\n");
      out.write("\t\t\t<div class=\"logo menu\" id=\"hello\">\n");
      out.write("\t\t\t\t<a href='#'>Wips-Inspect </a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"head-mobile\"></div>\n");
      out.write("\t\t\t<div class=\"button\"></div>\n");
      out.write("\t\t\t<ul>\n");
      out.write("\t\t\t\t<li><a href='#'>MENU</a>\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t<li id=\"profile\" class=\"menu\"><a href='#'>Profile</a></li>\n");
      out.write("\t\t\t\t\t\t<li id=\"config\" class=\"menu\"><a href='#'>Config</a></li>\n");
      out.write("\t\t\t\t\t\t<li id=\"inspect\" class=\"menu\"><a href='#'>Inspect</a></li>\n");
      out.write("\t\t\t\t\t\t<li id=\"monitor\" class=\"menu\"><a href='#'>Monitor</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<li id=\"setting\" class=\"menu\"><a href='#'>SETTING</a></li>\n");
      out.write("\t\t\t\t<li id=\"help\"><a href='#'>HELP</a>\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t<li><a href='#'>Product 1</a>\n");
      out.write("\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href='#'>Sub Product</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href='#'>Sub Product</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\t\t<li><a href='#'>Product 2</a>\n");
      out.write("\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href='#'>Sub Product</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href='#'>Sub Product</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</nav>\n");
      out.write("\t</header>\n");
      out.write("\t<div id=\"content\" class=\"content\"></div>\n");
      out.write("\t<!-- \n");
      out.write("\t<section\n");
      out.write("\t\tstyle='padding-top: 20px; font: bold 44px arial; color: #68D800;'>\n");
      out.write("\t\tResponsive CSS3 Menu <br />Dropdown + Submenus <br /> Width Toggle\n");
      out.write("\t\tAnimation\n");
      out.write("\t</section>\n");
      out.write("\t-->\n");
      out.write("\t<script src=\"js/menu2/js/index.js\"></script>\t\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t$(function() {\n");
      out.write("\t\t$(\".menu\").click(function(e) {\n");
      out.write("\t\t\te.preventDefault();\n");
      out.write("//\t\t\t$(\"#content\").html(\"\");\n");
      out.write("\t\t\t$(\"#content\").load(this.id+\".jsp\");\n");
      out.write("\t\t})\n");
      out.write("\t});\n");
      out.write("\t</script>\t\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
