/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M15
 * Generated at: 2017-03-01 08:00:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.M;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class add_005fconfig_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/M/header.jsp", Long.valueOf(1488355244000L));
    _jspx_dependants.put("/M/footer.jsp", Long.valueOf(1488329390000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<head>\n");
      out.write("\t<meta charset=\"UTF-8\">\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\t<title>Wips-Inspect</title>\n");
      out.write("\t<!-- jquery -->\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/jquery/1.11.1/jquery-1.11.1.min.js\"></script>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/js/jquery/ui/jquery-ui-1.12.1/jquery-ui.css\">\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/jquery/ui/jquery-ui-1.12.1/jquery-ui.js\"></script>\n");
      out.write("\t<!-- json2html -->\t\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/jquery.json2html.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/json2html.js\"></script>\t\t\n");
      out.write("\t<!-- https://cdnjs.com/libraries/c3  -->\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/js/c3/0.4.11/c3.min.css\"/>\t\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/d3/d3.v3.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/c3/0.4.11/c3.min.js\"></script>\n");
      out.write("\t<!-- icheck -->\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/icheck/icheck.min.js\"></script>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/js/icheck/skins/all.css\">\n");
      out.write("\t<!-- tablesorter -->\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/js/tablesorter-master/css/theme.default.css\">\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/tablesorter-master/js/jquery.tablesorter.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/tablesorter-master/js/jquery.tablesorter.widgets.js\"></script>\n");
      out.write("\t<!-- my js -->\n");
      out.write("\t<script src=\"/js/multiCharts.js\"></script>\n");
      out.write("\t<script src=\"/js/get_set.js\"></script>\n");
      out.write("\t<script src=\"/js/err.js\"></script>\n");
      out.write("\t<script src=\"/js/wifi_protocol.js\"></script>\t\n");
      out.write("\t<script src=\"/js/inspectChart.js\"></script>\n");
      out.write("\t<style type=\"text/css\">\n");
      out.write("\t* {\n");
      out.write("\t\tfont: 13px/18px Arial, Sans-serif;\n");
      out.write("\t\tfont-weight: bold;\n");
      out.write("\t}\n");
      out.write("\ttable.tablesorter thead tr th {\n");
      out.write("\t\tbackground: #1F497D;\n");
      out.write("    color: #fff;\n");
      out.write("\t}\n");
      out.write("\ttable.tablesorter thead tr, table.tablesorter tbody tr {\n");
      out.write("\t\tcursor: pointer;\n");
      out.write("    height: 35px;\n");
      out.write("\t}\n");
      out.write("\ttable.tablesorter tbody tr.selected td {\n");
      out.write("    background: none repeat scroll 0 0 #FF9900;\n");
      out.write("\t}\n");
      out.write("\timg {\n");
      out.write("\t\tvertical-align: middle;\n");
      out.write("\t}\n");
      out.write("\tinput {\n");
      out.write("\t\tvertical-align: middle;\n");
      out.write("\t}\n");
      out.write("\tinput[type=text], select {\n");
      out.write("\t    width: 90%;\n");
      out.write("\t    padding: 3px 5px;\n");
      out.write("\t    display: inline-block;\n");
      out.write("\t    border: 1px solid #ccc;\n");
      out.write("\t    border-radius: 4px;\n");
      out.write("\t    box-sizing: border-box;\n");
      out.write("\t    background: #fff;\n");
      out.write("\t}\n");
      out.write("\t.action_img {\n");
      out.write("\t\tcursor: pointer;\n");
      out.write("\t\twidth: 30px;\n");
      out.write("\t}\n");
      out.write("\t.table_img {\n");
      out.write("\t\tpadding: 0px;\n");
      out.write("\t\tmargin: 0px;\n");
      out.write("\t\tcursor: pointer;\n");
      out.write("\t\twidth: 20px;\n");
      out.write("\t}\n");
      out.write("\t.main_fieldset {\n");
      out.write("\t\tbackground: #ddd;\n");
      out.write("\t\tborder: 2px solid #1F497D;\n");
      out.write("\t\tborder-radius: 5px;\n");
      out.write("\t\tmargin-top: 10px;\n");
      out.write("\t\tmargin-bottom: 10px;\n");
      out.write("\t\tpadding: 10px;\n");
      out.write("\t}\n");
      out.write("\t.main_fieldset > legend {\n");
      out.write("\t\tbackground: #1F497D;\n");
      out.write("    color: #fff;\n");
      out.write("    padding: 5px 10px ;\n");
      out.write("    font-size: 18px;\n");
      out.write("    border-radius: 5px;\n");
      out.write("    box-shadow: 0 0 0 5px #ddd;\n");
      out.write("    margin-left: 20px;\n");
      out.write("\t}\n");
      out.write("\t.sub_fieldset {\n");
      out.write("\t\tbackground: #ddd;\n");
      out.write("\t\tborder: 2px solid #666C73;\n");
      out.write("\t\tborder-radius: 5px;\n");
      out.write("\t\tmargin-top: 10px;\n");
      out.write("\t\tmargin-bottom: 10px;\n");
      out.write("\t\tpadding: 10px;\n");
      out.write("\t}\n");
      out.write("\t.sub_fieldset > legend {\n");
      out.write("\t\tbackground: #666C73;\n");
      out.write("\t\tcolor: #fff;\n");
      out.write("\t\tpadding: 5px 10px ;\n");
      out.write("\t\tfont-size: 15px;\n");
      out.write("\t\tborder-radius: 5px;\n");
      out.write("\t\tbox-shadow: 0 0 0 5px #ddd;\n");
      out.write("\t\tmargin-left: 20px;\n");
      out.write("\t}\n");
      out.write("\t.title {\n");
      out.write("\t\tcursor: pointer;\n");
      out.write("\t\tvertical-align: middle;\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t\tpadding: 5px;\n");
      out.write("\t}\n");
      out.write("\t.title_img {\t\t\n");
      out.write("\t\twidth: 30px;\n");
      out.write("\t}\n");
      out.write("\t</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<table class=\"title\">\n");
      out.write("\t<tr>\n");
      out.write("\t\t<td><img class=\"title_img\" src=\"/img/M/internet.svg\"></td>\n");
      out.write("\t\t<td><b>WIPS INSPECTOR</b></td>\n");
      out.write("\t</tr>\n");
      out.write("</table>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("function gogo(page) {\n");
      out.write("\t$(\"body\").animate({\n");
      out.write("\t\t\"opacity\": \"0\",\n");
      out.write("\t\t\"top\": \"10px\"\n");
      out.write("\t},400, function () {\n");
      out.write("\t\tlocation.href = page;\n");
      out.write("\t});\n");
      out.write("}\n");
      out.write("\n");
      out.write("$(function() {\n");
      out.write("\t$(\".title\").click(function() {\n");
      out.write("\t\tgogo(\"index.jsp\");\n");
      out.write("\t});\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("</body>");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("#tabs {\n");
      out.write("\tpadding-left: 0px;\n");
      out.write("\tmargin-top: 10px;\n");
      out.write("\tbackground: none;\n");
      out.write("\tborder-width: 0px;\n");
      out.write("} \n");
      out.write("#tabs .ui-tabs-nav { \n");
      out.write("\tpadding-left: 0px;\n");
      out.write("\tbackground: transparent;\n");
      out.write("}\n");
      out.write("#tabs img {\n");
      out.write("\tvertical-align: middle;\n");
      out.write("\tpadding: 6px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<fieldset class=\"main_fieldset\">\n");
      out.write("\t\t<legend>New Config</legend>\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<input type=\"text\" id=\"new_config_name\">\n");
      out.write("\t\t\t<img class=\"action_img\" src=\"/img/M/save.png\" id=\"save_config\">\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<form id=\"config_form\">\n");
      out.write("\t\t\t<div id=\"tabs\" class=\"tab_header\">\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t<a href=\"#shooter_tab\">\n");
      out.write("\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n");
      out.write("\t\t\t\t\t\t\tShooter\n");
      out.write("\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n");
      out.write("\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t<img src=\"/img/gree_add.png\" class=\"table_img add_config_img\" target=\"shooter_tab\">\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t<a href=\"#capture_tab\">\n");
      out.write("\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n");
      out.write("\t\t\t\t\t\t\tCapture\n");
      out.write("\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n");
      out.write("\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t<img src=\"/img/gree_add.png\" class=\"table_img add_config_img\" target=\"capture_tab\">\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<div id=\"shooter_tab\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"capture_tab\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</form>\n");
      out.write("\t</fieldset>\n");
      out.write("\n");
      out.write("\t");
      out.write("\n");
      out.write("\t<table id=\"sample_tag\">\n");
      out.write("\t\t<thead></thead>\n");
      out.write("\t\t<tbody>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t<td align=\"right\"><img src=\"/img/red_remove.png\" class=\"table_img del_tag_img\"></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td>id</td>\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"tag_id\"></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td>length</td>\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"tag_length\"></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td>value</td>\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"tag_value\"></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t</tbody>\n");
      out.write("\t</table>\n");
      out.write("\n");
      out.write("\t");
      out.write("\n");
      out.write("\t<fieldset id=\"sample_config\" class=\"sub_fieldset sample_config\" style=\"display: none;\">\n");
      out.write("\t\t<legend>Config</legend>\n");
      out.write("\t\t<img class=\"table_img del_config_img\" src=\"/img/M/trash.png\" align=\"right\">\n");
      out.write("\t\t<table>\n");
      out.write("\t\t\t<thead></thead>\n");
      out.write("\t\t\t<tbody>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td width=\"100px;\">enable</td>\n");
      out.write("\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t<select name=\"enable\">\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">enable</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"0\">disable</option>\n");
      out.write("\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td>desc</td>\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"desc\"></td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td>dwell (msec)</td>\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"dwell\"></td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td>channel</td>\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"channel\"></td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td>frame</td>\n");
      out.write("\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t<select name=\"frame\" data-placeholder=\"Choose a Frame Type...\" class=\"frametype\">\n");
      out.write("\t\t\t\t\t\t\t<optgroup label='Management Frames'>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='00'>Association Request</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='01'>Association Response</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='02'>Reassociation Request</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='03'>Reassociation Response</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='04'>Probe Request</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='05'>Probe Response</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='08'>Beacon</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='09'>ATIM</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='0a'>Disassociation</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='0b'>Authentication</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='0c'>Deauthentication</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='0d'>Action</option>\n");
      out.write("\t\t\t\t\t\t\t</optgroup>\n");
      out.write("\t\t\t\t\t\t\t<optgroup label='Control Frames'>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='18'>Block Ack Request</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='19'>Block Ack</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='1a'>PS-Poll</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='1b'>RTS</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='1c'>CTS</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='1d'>ACK</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='1e'>CF End</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='1f'>CF End Ack</option>\n");
      out.write("\t\t\t\t\t\t\t</optgroup>\n");
      out.write("\t\t\t\t\t\t\t<optgroup label='Data Frames'>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='20'>Data</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='21'>Data Ack</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='22'>Data Poll</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='23'>Data Ack Poll</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='24'>NULL</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='25'>ACK</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='26'>Poll</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='27'>Ack Poll</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='28'>Qos Data</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='29'>Qos Data Ack</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='2a'>Qos Data Poll</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='2b'>Qos Data Ack Poll</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='2c'>Qos NULL</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='2e'>Qos Poll</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='2f'>Qos Ack</option>\n");
      out.write("\t\t\t\t\t\t\t</optgroup>\n");
      out.write("\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td>ds</td>\n");
      out.write("\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t<select name=\"ds\">\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"\">Not Set</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"00\">ADHOC (management)</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"10\">From DS</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"01\">To DS</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"11\">WDS</option>\n");
      out.write("\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td>addr</td>\n");
      out.write("\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t<select name=\"address\" class=\"address\">\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">Not set</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"any_addr\">ANY</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"apsta\">AP/STA</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"addr1\">ADDRESS 1</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"addr2\">ADDRESS 2</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"addr3\">ADDRESS 3</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"addr4\">ADDRESS 4</option>\n");
      out.write("\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t<div class=\"addr addr1\">\n");
      out.write("\t\t\t\t\t\t\t<table>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>da</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"addr1_da\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"addr addr2\">\n");
      out.write("\t\t\t\t\t\t\t<table>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>da</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"addr2_da\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>sa</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"addr2_sa\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"addr addr3\">\n");
      out.write("\t\t\t\t\t\t\t<table>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>bssid</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"addr3_bssid\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>da</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"addr3_da\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>sa</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"addr3_sa\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"addr addr4\">\n");
      out.write("\t\t\t\t\t\t\t<table>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>da</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"addr4_da\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>sa</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"addr4_sa\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>ta</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"addr4_ta\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>ra</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"addr4_ra\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"addr apsta\">\n");
      out.write("\t\t\t\t\t\t\t<table>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>ap</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"ap\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>sta</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"sta\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"addr any_addr\">\n");
      out.write("\t\t\t\t\t\t\t<table>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>any</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"any_addr\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td valign=\"top\">tag <img src=\"/img/gree_add.png\" class=\"table_img add_tag_img\"></td>\n");
      out.write("\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t<div class=\"tag_div\"></div>\n");
      out.write("\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t</tbody>\n");
      out.write("\t\t</table>\n");
      out.write("\t</fieldset>\n");
      out.write("\n");
      out.write("\t<a id=\"submit\" href=\"#\">submit</a>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("$(document).ready(function() {\n");
      out.write("\t$( \"#tabs\" ).tabs({\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t$(\".add_tag_img\").click(function() {\n");
      out.write("\t\tvar c = $(\"#sample_tag\").clone(true);\n");
      out.write("\t\tc.find(\"input\").val(\"\");\n");
      out.write("\t\tvar $pp = $(this).parent().parent();\n");
      out.write("\t\tvar $t = $pp.find(\".tag_div\");\n");
      out.write("\t\tc.css({display:'none'});\n");
      out.write("\t\tc.prependTo($t).show(\"slow\");\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t$(\".del_tag_img\").click(function() {\n");
      out.write("\t\tvar $pppp = $(this).parent().parent().parent().parent();\n");
      out.write("\t\t$pppp.hide(\"slow\", function() { $pppp.remove(); });\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t$(\".add_config_img\").click(function() {\n");
      out.write("\t\tvar c = $(\"#sample_config\").clone(true);\n");
      out.write("\t\tc.find(\"input\").val(\"\");\n");
      out.write("\t\tvar t = $(this).attr(\"target\");\n");
      out.write("\t\tc.css({display:'none'});\n");
      out.write("\t\tc.prependTo($(\"#\"+t)).slideDown(\"slow\");\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t$(\".del_config_img\").click(function() {\n");
      out.write("\t\tvar $p = $(this).parent();\n");
      out.write("\t\t$p.slideUp(\"slow\", function() { $p.remove(); });\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t$(\"#submit\").click(function() {\n");
      out.write("\t\t$.post(\"submit.jsp\", $(\"#config_form\").serialize())\n");
      out.write("\t\t\t.done(function(result) {\n");
      out.write("\t\t\t\talert(\"ok\");\n");
      out.write("\t\t});\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t$(\".addr\").hide();\n");
      out.write("\t$(\".address\").change(function() {\n");
      out.write("\t\tvar $p = $(this).parent();\n");
      out.write("\t\t\n");
      out.write("\t\t$p.find(\".addr\").hide();\n");
      out.write("\t\t\n");
      out.write("\t\tvar type = $(this).val();\n");
      out.write("\t\tif (type == \"any_addr\") {\n");
      out.write("\t\t\t$p.find(\".any_addr\").slideDown(\"slow\");\n");
      out.write("\t\t} else if (type == \"apsta\") {\n");
      out.write("\t\t\t$p.find(\".apsta\").slideDown(\"slow\");\n");
      out.write("\t\t} else if (type == \"addr1\") {\n");
      out.write("\t\t\t$p.find(\".addr1\").slideDown(\"slow\");\n");
      out.write("\t\t} else if (type == \"addr2\") {\n");
      out.write("\t\t\t$p.find(\".addr2\").slideDown(\"slow\");\n");
      out.write("\t\t} else if (type == \"addr3\") {\n");
      out.write("\t\t\t$p.find(\".addr3\").slideDown(\"slow\");\n");
      out.write("\t\t} else if (type == \"addr4\") {\n");
      out.write("\t\t\t$p.find(\".addr4\").slideDown(\"slow\");\n");
      out.write("\t\t}\n");
      out.write("\t});\t\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("$(function() {\n");
      out.write("\t$(\".link\").click(function() {\n");
      out.write("\t\tvar param = \"\";\n");
      out.write("\t\tvar call = $(this).attr(\"call\");\n");
      out.write("\t\tif (call != undefined) {\n");
      out.write("\t\t\tparam = eval(call+\"()\")\n");
      out.write("\t\t\tparam = \"?\"+eval(call+\"()\");\n");
      out.write("\t\t}\n");
      out.write("\t\tvar page = $(this).attr(\"page\");\n");
      out.write("\t\tif (page != undefined) {\n");
      out.write("\t\t\t$(\"body\").animate({\n");
      out.write("\t\t\t\t\"opacity\": \"0\",\n");
      out.write("\t\t\t\t\"top\": \"10px\"\n");
      out.write("\t\t\t},400, function () {\n");
      out.write("\t\t\t\tlocation.href = page+param;\n");
      out.write("\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("});\n");
      out.write("\n");
      out.write("</script>");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
